# Generated by Django 5.2.13 on 2026-04-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_is_emergency_appointment_is_serving_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='Appointment',
        ),
        migrations.AlterModelTable(
            name='doctoravailability',
            table='DoctorAvailability',
        ),
        migrations.AlterModelTable(
            name='doctorleave',
            table='DoctorLeave',
        ),
        migrations.AlterModelTable(
            name='doctorprofile',
            table='DoctorProfile',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='Patient',
        ),
        migrations.AlterModelTable(
            name='specialization',
            table='Specialization',
        ),
    ]
