# Generated by Django 5.2.13 on 2026-04-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_appointment_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_walkin',
            field=models.BooleanField(default=False),
        ),
    ]
