# Generated by Django 5.2.13 on 2026-04-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
