# Generated by Django 5.2.13 on 2026-04-18 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_patient_email'),
        ('queue_management', '0002_queue_is_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='appointments.appointment'),
        ),
    ]
