# Generated by Django 5.2.13 on 2026-04-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_management', '0003_alter_queue_appointment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='queue',
            table='Queue',
        ),
    ]
