# Generated by Django 5.2.13 on 2026-04-13 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0002_remove_doctorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.doctorprofile'),
        ),
    ]
